seed : 42
out_dir : "../results/comp_algos"
data_path : "../dataset_/final_E4/"

BANDS_MAX:
   "a":
     - 0
     - 1
   "b":
      - 0
      - 1
      - 2
   "c":
      - 0
      - 1
      - 3
   "d":
      - 0
      - 1
      - 4
   "e":
      - 0
      - 1
      - 5
   "f":
      - 0
      - 1
      - 3
      - 4
      - 5
   "g":
      - 6
      - 7
   "h":
      - 0
      - 1
      - 6
      - 7
   "h_bis":
      - 0
      - 1
      - 2
      - 6
      - 7
      - 8
   "i":
      - 0
      - 1
      - 4
      - 6
      - 7
   "i_dem":
      - 0
      - 1
      - 3
      - 6
      - 7
   "i_ori":
      - 0
      - 1
      - 5
      - 6
      - 7
   "j":
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8


import : 
    - "from sklearn.neighbors import KNeighborsClassifier"
    - "from statistical_descriptor import *"

name_pip: 
    - "KNN_direct"

pipeline:
# KNN 
    - - - "Hist_SAR"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1
