seed : 42
out_dir : "../results/comp_stats"
data_path : "../dataset_/final_E4/"

BANDS_MAX:
   "h":
      - 0
      - 1
      - 6
      - 7
    
import : 
    - "from sklearn.neighbors import KNeighborsClassifier"
    - "from statistical_descriptor import *"

name_pip: 
    - "KNN_direct_mean"
    - "KNN_direct_meanstd"
    - "KNN_direct_meanstdskew"
    - "KNN_direct_meanstdskewkurt"


pipeline:
# KNN 
    - - - "Stats_SAR"
        - type_stats: "mean"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1

    - - - "Stats_SAR"
        - type_stats: "std"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1

    - - - "Stats_SAR"
        - type_stats: "skew"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1
    
    - - - "Stats_SAR"
        - type_stats: "kurtosis"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1

    